### ISSUE TITLE
Load ONNX model zoo failed:Protobuf parsing failed.

### ISSUE THREAD

**Issue by dujtep-airtech** [ilpropheta/onnxruntime-demo#1]
I have done to use onnxruntime-demo. if i try to load model from onnx model zoo. it got error as below
"onnx/squeezenet/model/squeezenet1.1-7.onnx failed:Protobuf parsing failed."

**Comment by ValeSo95** [comment]
Hi, 
i have the same problem with a resnet18. How have you solved this problem?
